### ISSUE TITLE
Issue during package build

### ISSUE THREAD

**Issue by d4nielhdz** [symphony-org/frost#49]
I get an error after running `stack install` that stops the project build. Here's the log:
`ghc: loadArchive: Neither an archive, nor a fat archive: `/nix/store/a76n8l1caynyyngdpnyihlrgyr9k9ilg-clang-wrapper-7.1.0/bin/clang++'
ghc: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-apple-darwin):
	loadArchive "/nix/store/a76n8l1caynyyngdpnyihlrgyr9k9ilg-clang-wrapper-7.1.0/bin/clang++": failed

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug`

Any idea on how to fix this?

**Comment by lukasz-golebiewski** [comment]
I'm not getting this on linux. @rabbitonweb or @dzajkowski could you give `stack install` a go on mac OS?

**Comment by lukasz-golebiewski** [comment]
@d4nielhdz does the issue persist after switching https://github.com/frost-org/frost/blob/38e1660400e0d0e2421a7d08c65cdedf88cd03ce/stack.yaml#L15 to `false`?

**Comment by EncodePanda** [comment]
I have the same issue on my Mac. I've disabled `nix` integration for now, but this has to be resolved asap. Updating channels to the most recent ones did not help.

**Comment by EncodePanda** [comment]
Hi @d4nielhdz  I've finally managed to fix the issue on the OSX. Those are two known issues in the Haskell community that have not been resolved o_0. Anyway, workarounds that I found on the web seem to work. 

Could you please please check that it works on your machine as well?

**Comment by mjuchli** [comment]
@EncodePanda do you remember the workaround?

**Comment by EncodePanda** [comment]
> @EncodePanda do you remember the workaround?

this https://github.com/symphony-org/frost/pull/68
